import { NextRequest, NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req: NextRequest) {
  try {
    const { email, results } = await req.json();

    if (!email || !results || !Array.isArray(results)) {
      return NextResponse.json({ error: "Missing email or results" }, { status: 400 });
    }

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "smtp.ethereal.email",
      port: Number(process.env.SMTP_PORT) || 587,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    let htmlContent = `
      <div style="font-family: Arial, sans-serif; color: #333; max-w: 600px; margin: 0 auto;">
        <h2 style="color: #4f46e5;">YouTube Intelligence Report</h2>
        <p>Here are the latest analysis results for your requested URLs.</p>
        <hr style="border: 1px solid #eee;" />
    `;

    for (const res of results) {
      if (res.error) {
        htmlContent += `
          <div style="margin-bottom: 20px;">
            <h4 style="color: #e11d48; margin-bottom: 4px;">Error: ${res.url}</h4>
            <p style="margin-top: 0; font-size: 14px;">${res.error}</p>
          </div>
        `;
      } else {
        htmlContent += `
          <div style="margin-bottom: 20px; padding: 15px; background-color: #f8fafc; border-radius: 8px; border-left: 4px solid #4f46e5;">
            <h4 style="margin-top: 0; margin-bottom: 8px; color: #1e293b;">URL: <a href="${res.url}">${res.url}</a></h4>
            <p style="margin-top: 0; font-size: 14px;"><strong>Metric:</strong> ${res.metric} (${res.sentiment.pro}% Pro)</p>
            <p style="font-size: 14px; line-height: 1.5;"><strong>Summary:</strong><br/>${res.summary}</p>
            <div style="font-size: 13px; color: #475569; margin-top: 10px;">
              <strong>Sentiment:</strong> Pro: ${res.sentiment.pro}% | Neutral: ${res.sentiment.neutral}% | Con: ${res.sentiment.con}%
            </div>
          </div>
        `;
      }
    }

    htmlContent += `
        <hr style="border: 1px solid #eee;" />
        <p style="font-size: 12px; color: #94a3b8; text-align: center;">Generated by YouTube Intelligence</p>
      </div>
    `;

    await transporter.sendMail({
      from: `"YouTube Intelligence" <${process.env.SMTP_USER}>`,
      to: email.split(',').map((e: string) => e.trim()).join(','),
      subject: "YouTube Intelligence Analysis Report",
      html: htmlContent,
    });

    return NextResponse.json({ success: true });

  } catch (error: any) {
    console.error("Email send error:", error);
    return NextResponse.json({ error: error.message || "Failed to send email" }, { status: 500 });
  }
}
